import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider
} from '@clerk/nextjs'


const inter = Inter({
 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body
          className={`${inter.className} antialiased`}
        >
         <div className="min-h-screen flex w-full flex-col items-center dark:bg-black">
         {children}
         </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
